codecov:
  require_ci_to_pass: yes
  max_report_age: off
  token: d1605a8b-7546-44e6-8e50-17dc540b4532

coverage:
  precision: 2
  round: down
  range: 50..90
  status:
    project:
      default:
       enabled: no
       threshold: 0.2
       if_not_found: success
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success
